/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyCertificateRouteImport } from './routes/verify-certificate'
import { Route as StudentZoneRouteImport } from './routes/student-zone'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AdmissionRouteImport } from './routes/admission'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentResultsRouteImport } from './routes/student.results'
import { Route as StudentOnlineTestRouteImport } from './routes/student.online-test'
import { Route as StudentLoginRouteImport } from './routes/student.login'
import { Route as StudentFeesRouteImport } from './routes/student.fees'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentCertificatesRouteImport } from './routes/student.certificates'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'

const VerifyCertificateRoute = VerifyCertificateRouteImport.update({
  id: '/verify-certificate',
  path: '/verify-certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentZoneRoute = StudentZoneRouteImport.update({
  id: '/student-zone',
  path: '/student-zone',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRoute = AdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentResultsRoute = StudentResultsRouteImport.update({
  id: '/student/results',
  path: '/student/results',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentOnlineTestRoute = StudentOnlineTestRouteImport.update({
  id: '/student/online-test',
  path: '/student/online-test',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student/login',
  path: '/student/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentFeesRoute = StudentFeesRouteImport.update({
  id: '/student/fees',
  path: '/student/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCertificatesRoute = StudentCertificatesRouteImport.update({
  id: '/student/certificates',
  path: '/student/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/student/attendance',
  path: '/student/attendance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admission': typeof AdmissionRoute
  '/courses': typeof CoursesRoute
  '/downloads': typeof DownloadsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student-zone': typeof StudentZoneRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/login': typeof StudentLoginRoute
  '/student/online-test': typeof StudentOnlineTestRoute
  '/student/results': typeof StudentResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admission': typeof AdmissionRoute
  '/courses': typeof CoursesRoute
  '/downloads': typeof DownloadsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student-zone': typeof StudentZoneRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/login': typeof StudentLoginRoute
  '/student/online-test': typeof StudentOnlineTestRoute
  '/student/results': typeof StudentResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admission': typeof AdmissionRoute
  '/courses': typeof CoursesRoute
  '/downloads': typeof DownloadsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student-zone': typeof StudentZoneRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/login': typeof StudentLoginRoute
  '/student/online-test': typeof StudentOnlineTestRoute
  '/student/results': typeof StudentResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admission'
    | '/courses'
    | '/downloads'
    | '/sitemap.xml'
    | '/student-zone'
    | '/verify-certificate'
    | '/student/attendance'
    | '/student/certificates'
    | '/student/dashboard'
    | '/student/fees'
    | '/student/login'
    | '/student/online-test'
    | '/student/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admission'
    | '/courses'
    | '/downloads'
    | '/sitemap.xml'
    | '/student-zone'
    | '/verify-certificate'
    | '/student/attendance'
    | '/student/certificates'
    | '/student/dashboard'
    | '/student/fees'
    | '/student/login'
    | '/student/online-test'
    | '/student/results'
  id:
    | '__root__'
    | '/'
    | '/admission'
    | '/courses'
    | '/downloads'
    | '/sitemap.xml'
    | '/student-zone'
    | '/verify-certificate'
    | '/student/attendance'
    | '/student/certificates'
    | '/student/dashboard'
    | '/student/fees'
    | '/student/login'
    | '/student/online-test'
    | '/student/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmissionRoute: typeof AdmissionRoute
  CoursesRoute: typeof CoursesRoute
  DownloadsRoute: typeof DownloadsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudentZoneRoute: typeof StudentZoneRoute
  VerifyCertificateRoute: typeof VerifyCertificateRoute
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentCertificatesRoute: typeof StudentCertificatesRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentFeesRoute: typeof StudentFeesRoute
  StudentLoginRoute: typeof StudentLoginRoute
  StudentOnlineTestRoute: typeof StudentOnlineTestRoute
  StudentResultsRoute: typeof StudentResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-certificate': {
      id: '/verify-certificate'
      path: '/verify-certificate'
      fullPath: '/verify-certificate'
      preLoaderRoute: typeof VerifyCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-zone': {
      id: '/student-zone'
      path: '/student-zone'
      fullPath: '/student-zone'
      preLoaderRoute: typeof StudentZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission': {
      id: '/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/results': {
      id: '/student/results'
      path: '/student/results'
      fullPath: '/student/results'
      preLoaderRoute: typeof StudentResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/online-test': {
      id: '/student/online-test'
      path: '/student/online-test'
      fullPath: '/student/online-test'
      preLoaderRoute: typeof StudentOnlineTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/login': {
      id: '/student/login'
      path: '/student/login'
      fullPath: '/student/login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/fees': {
      id: '/student/fees'
      path: '/student/fees'
      fullPath: '/student/fees'
      preLoaderRoute: typeof StudentFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/certificates': {
      id: '/student/certificates'
      path: '/student/certificates'
      fullPath: '/student/certificates'
      preLoaderRoute: typeof StudentCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/student/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmissionRoute: AdmissionRoute,
  CoursesRoute: CoursesRoute,
  DownloadsRoute: DownloadsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudentZoneRoute: StudentZoneRoute,
  VerifyCertificateRoute: VerifyCertificateRoute,
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentCertificatesRoute: StudentCertificatesRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentFeesRoute: StudentFeesRoute,
  StudentLoginRoute: StudentLoginRoute,
  StudentOnlineTestRoute: StudentOnlineTestRoute,
  StudentResultsRoute: StudentResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
